__include__: [../dfine_n.yaml]
epochs: 100
eval_spatial_size: [704, 704]
HGNetv2:
  pretrained: false
lr_scheduler:
  milestones: [80]
train_dataloader:
  total_batch_size: 16
  dataset:
    transforms:
      policy: {epoch: 88}
  collate_fn:
    base_size: 704
    base_size_repeat: null
    stop_epoch: 88
val_dataloader:
  total_batch_size: 16
