services:
  yolo-trainer:
    build:
      context: ../../
      dockerfile: docker/yolo/Dockerfile

    working_dir: /workspace

    volumes:
      - ../../:/workspace

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]

    stdin_open: true
    tty: true

    shm_size: "8gb"

    command: bash
